### PR TITLE
Replace `async_once` with `tokio::sync::OnceCell`

### PR DESCRIPTION
**Pull request by Expyron**
`async_once` is unmaintained and [has been reported unsound](https://github.com/hjiayz/async_once/issues/5).

`tokio`'s `parking_lot` feature has been added in order to have access to `OnceCell::const_new()`. This is only necessary in older `tokio` versions.

### CODE REVIEW

**Comment by abr-egn** [comment]
Thank you for contributing this!  I've authorized an evergreen run and assuming that passes I'll merge this in.

**Comment by abr-egn** [comment]
It looks like this doesn't compile with the `sync` feature enabled, and also needs a pass through `rustfmt +nightly --unstable-features`.  Once those are fixed I can merge this :)

**Comment by Expyron** [comment]
I pushed an update:
- Ran `rustfmt`
- I'm not sure what happened with the `sync` feature, but I don't think it was the changes in that PR. I tried to fix it by updating the `log` dependency, which was what caused an issue on my machine. If it fails again, can you share the error message?

**Comment by abr-egn** [comment]
Sorry, forgot that evergreen runs aren't publicly visible!  Running `cargo check --tests --features tokio-sync` will reproduce the errors:
```
error[E0618]: expected function, found `get_client_options`
  --> src/sync/test.rs:64:19
   |
39 | / lazy_static! {
40 | |     static ref get_client_options: ClientOptions =
41 | |         runtime::block_on(async { crate::test::get_client_options().await.clone() });
42 | | }
   | |_- `sync::test::get_client_options` defined here
...
64 |       let options = get_client_options().clone();
   |                     ^^^^^^^^^^^^^^^^^^--
   |                     |
   |                     call expression requires function

... etc ...
```

**Comment by Expyron** [comment]
Pushed an update fixing the sync tests

**Review by abr-egn — APPROVED** [review]
LGTM!  Tagging in Isabel.

**Pull request merged**
