### PR TITLE
chore: fix clippy `1.67`

### PR DESCRIPTION
**Pull request by attila-lin**

### CODE REVIEW

**Comment by kmahar** [comment]
Hi @attila-lin, thanks for the contribution! 

A lot of these changes appear to be applying a new nightly-only rule `uninlined_format_args`. Unfortunately, that rule forces inlined format arguments which were not introduced until Rust 1.58, and our MSRV is 1.57. 

However, there are some other changes in this PR that we can certainly apply now.

It seems what we should do is add a [clippy.toml](https://doc.rust-lang.org/clippy/configuration.html#specifying-the-minimum-supported-rust-version) file specifying our MSRV. Would you be up for adding that and removing the `uninlined_format_args` changes, and also editing the file `.evergreen/check-clippy.sh` to set `CLIPPY_VERSION` to 1.66?

**Comment by attila-lin** [comment]
Yes！ Thanks for your response.

**Review by kmahar — APPROVED** [review]
LGTM! Tagging in the the rest of the team for review.

**Review by abr-egn — APPROVED** [review]
LGTM, thank you!

**Review by isabelatkinson — APPROVED** [review]

**Comment by kmahar** [comment]
thank you for the contribution @attila-lin!

**Pull request merged**
