### PR TITLE
RUST-1588 Add Namespace and id in GetMoreResult

### PR DESCRIPTION
**Pull request by drshika**

### CODE REVIEW

**Review by abr-egn — APPROVED** [review]
LGTM!  The lint failure looks unrelated :)

**Review by isabelatkinson — COMMENTED** [review]
code changes LGTM, I assume this isn't the full implementation of RUST-1588? is the plan to do piecemeal PRs for this ticket?

**Comment by drshika** [comment]
> code changes LGTM, I assume this isn't the full implementation of [RUST-1588](https://jira.mongodb.org/browse/RUST-1588)? is the plan to do piecemeal PRs for this ticket?

Yes that is the plan!

**Review by isabelatkinson — APPROVED** [review]
> Yes that is the plan!

Sounds good, it might be helpful to make an outline of the PRs planned or file separate tickets to make sure we don't miss anything (but I'll leave that up to you & Abraham).

**Pull request merged**
