### PR TITLE
minor: bump dependencies

### PR DESCRIPTION
**Pull request by attila-lin**
…`strsim` to `0.11`

### CODE REVIEW

**Comment by isabelatkinson** [comment]
Hey @attila-lin, thanks for opening this PR! Would you mind rebasing/merging (either is fine) with the latest changes on main? The most recent commit there (#1141) has updates that are needed to run CI. Once that's pushed I can run another patch and merge this in if everything looks fine.

**Comment by attila-lin** [comment]
done~

**Comment by isabelatkinson** [comment]
The `strsim` bump broke one of our tests that validates URI option suggestions; there must've been a change in the `jaro_winkler` implementation. I'm going to push a commit to remove the failing comparison and then this should be good to go.

**Review by isabelatkinson — APPROVED** [review]
Thanks for your contribution @attila-lin!

**Pull request merged**
