### PR TITLE
Update the os_info crate version

### PR DESCRIPTION
**Pull request by DarkEld3r**
Additionally I have disabled the default features to (slightly) speedup compilation.

### CODE REVIEW

**Comment by DarkEld3r** [comment]
I'm not sure if I'm able to see the reason of CI failures.

**Comment by saghm** [comment]
They're not related to your patch; we had some issues with the async-std update, so we temporarily pinned to 1.5.x. Any chance you could rebase master, which should fix them?

**Comment by DarkEld3r** [comment]
@saghm Done.

**Comment by DarkEld3r** [comment]
It seems all checks have passed now. :green_circle:

**Pull request merged**
