### PR TITLE
RUST-696 Update to socket2 v0.4

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**

### CODE REVIEW

**Comment by agolin95** [comment]
Tracking as part of https://jira.mongodb.org/browse/RUST-696

**Comment by saghm** [comment]
Thanks for the pull request! It looks like there was a rebase conflict with a change we've made since you made the PR, so I rebased and pushed the conflict fix for that and authorized the CI run.

**Comment by Thomasdezeeuw** [comment]
The CI failed, but I can't see why.

**Comment by Thomasdezeeuw** [comment]
Can someone with access copy the logs?

**Review by patrickfreed — APPROVED** [review]
The CI failures look to be unrelated flakiness in our test runners, so this PR LGTM. Thanks for your contribution!

**Review by saghm — APPROVED** [review]

**Review by isabelatkinson — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
