### PR TITLE
Add deserialize-utf8-lossy feature to always deserialize using lossy UTF-8 conversion

### PR DESCRIPTION
**Pull request by tyilo**
Useful if you need to read from a collection created by a driver for another programming language.

See #799

### CODE REVIEW

**Comment by tyilo** [comment]
Also consider making this the default to improve interoperability with other drivers.

**Comment by abr-egn** [comment]
Thanks for the contribution!  I don't think we'll want to make this the default to avoid breaking anyone relying on the existing validation, but it seems quite helpful as an opt-in feature.

If you're willing, could you share more information about the situation that motivates this?  The bson spec says that strings are UTF-8, so at least in theory drivers shouldn't be writing values that require this.

**Comment by tyilo** [comment]
> If you're willing, could you share more information about the situation that motivates this? The bson spec says that strings are UTF-8, so at least in theory drivers shouldn't be writing values that require this.

Yes, I agree that in a perfect world this would be rejected by all drivers and also the MongoDB server itself.

However, at least the Java driver doesn't always produce valid UTF-8 when writing to a collection.
See https://jira.mongodb.org/projects/JAVA/issues/JAVA-5575 which has been closed as "Won't Fix".

**Review by abr-egn — APPROVED** [review]
LGTM!

**Comment by tyilo** [comment]
@isabelatkinson Doesn't seem to work for me:

```rust
use std::fmt::Debug;
use std::{error::Error, sync::LazyLock};

use bson::serde_helpers::Utf8LossyDeserialization;
use futures_util::TryStreamExt;
use mongodb::{
    bson::{doc, Document, RawDocumentBuf},
    Database,
};
use serde::de::DeserializeOwned;

const COLLECTION_NAME: &str = "document-registry:documents";
const FILTER: LazyLock<Document> = LazyLock::new(|| {
    doc! {
        ... // problem document
    }
});

async fn log_all<T: Send + Sync + DeserializeOwned + Debug>(database: &Database) -> Result<()> {
    let collection = database.collection::<T>(COLLECTION_NAME);
    let mut stream = collection.find(FILTER.clone()).await?;
    while let Some(raw) = stream.try_next().await? {
        println!("Raw document: {:#?}", raw);
    }
    Ok(())
}

#[tokio::main]
async fn main() -> Result<()> {
    let database = ...;

    log_all::<Utf8LossyDeserialization<Document>>(&database).await?;

    Ok(())
}
```

Output:
```
Error: Error { kind: BsonDeserialization(DeserializationError { message: "invalid utf-8 sequence of 1 bytes from index 0" }), labels: {}, wire_version: None, source: None }
```

**Comment by tyilo** [comment]
@isabelatkinson Seems to work great.

**Comment by isabelatkinson** [comment]
@tyilo great to hear. I just merged in the addition to the BSON library, and it will be included in that crate's next release. Going to close this out - thanks for bringing this issue to our attention!

**Pull request closed without merging**
