### PR TITLE
RUST-970 Upgrade to hmac 0.11

### PR DESCRIPTION
**Pull request by seanpianka**
Includes `hmac = "0.11"` and `pbkdf2 = "0.8"`

### CODE REVIEW

**Comment by patrickfreed** [comment]
Hi @seanpianka, thanks for the PR! Can you run `rustfmt` on the branch? Check out `.evergreen/check-rustfmt.sh` for the invocation we use.

**Comment by seanpianka** [comment]
@patrickfreed Thanks for the pointer, I've applied rustfmt and pushed the new commit.

**Comment by agolin95** [comment]
Tracked in https://jira.mongodb.org/browse/RUST-970

**Review by NBSquare — APPROVED** [review]
LGTM!

**Review by patrickfreed — APPROVED** [review]
LGTM, thanks for the contribution!

**Review by abr-egn — APPROVED** [review]
LGTM!

**Review by isabelatkinson — APPROVED** [review]

**Pull request merged**
