### PR TITLE
RUST-2097 Migrate from `derivative` to `derive-where`

### PR DESCRIPTION
**Pull request by isabelatkinson**
Migrates from `derivative` to `derive-where`. In the long term, I'd like to switch over to `derive_more`, which we already depend on for some `Display`-related utilities. `derive_more` has the largest feature set of crates of its ilk; however, its MSRV for the features we'd need is 1.75 (compared to our current 1.67), and it does not yet support `PartialEq`. We can make the swap once those concerns are resolved. This is tracked in RUST-2102.

### CODE REVIEW

**Review by abr-egn — APPROVED** [review]
LGTM!

**Comment by abr-egn** [comment]
> In the long term, I'd like to switch over to `derive_more`, which we already depend on for some `Display`-related utilities. `derive_more` has the largest feature set of crates of its ilk; however, its MSRV for the features we'd need is 1.75 (compared to our current 1.67), and it does not yet support `PartialEq`. We can make the swap once those concerns are resolved.

Can you file a ticket so we remember to do this?

**Comment by TroyKomodo** [comment]
Can we make a minor release of this `3.1.1` on crates.io @isabelatkinson

**Comment by isabelatkinson** [comment]
@TroyKomodo 3.1.1 was just released!

**Pull request merged**
