### PR TITLE
RUST-682 Update encryption dependencies

### PR DESCRIPTION
**Pull request by bugadani**
This PR leaves PBKDF2 at 0.6 instead of 0.7 to avoid bumping MSRV to 1.47.

### CODE REVIEW

**Comment by agolin95** [comment]
Tracked in https://jira.mongodb.org/browse/RUST-682

**Comment by jszwedko** [comment]
Just noting that this is required to resolve https://rustsec.org/advisories/RUSTSEC-2020-0146 due to the transient dependency through `sha2` -> `block-buffer` -> `generic-array`.

**Review by tobin-crypto — APPROVED** [review]
In regards to clearing the `generic-array` RUSTSEC advisory. I applied this to a local fork of `mongodb`. It builds and it removes the `cargo deny` error for a crate that depends on `mongodb`.

**Review by isabelatkinson — APPROVED** [review]
LGTM, tagging in the rest of the team for review!

**Review by saghm — COMMENTED** [review]
The code all looks good to me!

> This PR leaves PBKDF2 at 0.6 instead of 0.7 to avoid bumping MSRV to 1.47

@isabelatkinson @patrickfreed since we're doing this for our 2.0 release, do we think we should just bump this all the way and bump our minimum Rust version accordingly?

**Comment by patrickfreed** [comment]
Bumping pdbkf2 to 0.7 and the MSRV to 1.47 for driver 2.0 sounds good to me.

**Comment by isabelatkinson** [comment]
SGTM as well, @bugadani this will require some updates in our CI so I'll take it from here if that's alright with you!

**Review by saghm — APPROVED** [review]

**Review by patrickfreed — APPROVED** [review]

**Pull request merged**
